name: Gravity
on:
  push:
    branches:
      - main
      - master
  pull_request: {}

jobs:
  build:
    name: Run Gravity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4.1.0
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install
      - run: pnpm build
      - run: npx @gravityci/cli ./dist
        env:
          GRAVITY_TOKEN: ${{ secrets.GRAVITY_TOKEN }}